
## HARRIS
# Radius for non maxima supression in Harris keypoints detector
harris: True
harris_kps_radius: 10. #0.6 

# Radius for normals estimation
normals_radius: 10. #1.

# threshold value for detecting corners in Harris keypoints detector
harris_kps_thres: 1e-15 #1e-6

## SIFT
sift: False
sift_kps_min_scale: 1.0
sift_kps_n_octaves: 6
sift_kps_n_scales_per_octave: 4
sift_kps_min_contrast: 0.05

## SHOT
shot: True
# Radius for SHOT computation
shot_feats_radius: 15. # 50.

# Radius for normals estimation
normals_feats_radius: 15. #50.

# Radius for external local reference frames computation
lrf_feats_radius: 10. # 60.

## FPFH
fpfh: False
# Radius for FPFH computation
fpfh_feats_radius: 50.

# Radius for normals estimation
normals_feats_radius: 50.


## CORRESPONDENCE MATCHING
# maximum allowed distance between correspondences in keypoints
kps_cor_thres: 30.0

# maximum allowed distance between correspondences in features
feats_cor_thres: 40.0  # traditional methods
nn_feats_cor_thres: 0.091   # nn method

## KMEANS CLUSTERING 
k_means_clusters: 15

# max iteration number of GICP
gicp_iter: 3000